### ISSUE TITLE
Add Tomcat support for SSL

### ISSUE THREAD

**Issue by herau** [herau/diy-project#7]
Application configuration : 

```yml
server:
    ssl:
        key-store: sample.jks
        key-store-password: secret
        key-password: password
```
